#!/usr/bin/env python3

import subprocess
import requests
import time
import os

command="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep '^\s*SSID:' | awk '{print $2}'"
server=os.getenv('SPY_SERVER', 'http://localhost:5000')
interval=os.getenv('SPY_INTERVAL', 5)
lastNet=None

print("Started. Last net is: {}".format(lastNet))
while True:
    currentNet = subprocess.getoutput(command)
    if currentNet != lastNet:
        print("New net '{}' found".format(currentNet));
        network = {
            'fingerprint': currentNet,
            'kind': 'work' if currentNet == 'HackZurich' else 'personal',
            'action': 'connect',
        }
        requests.post("{}/ingest".format(server), json={'network':network})
        lastNet = currentNet
    time.sleep(interval)
