#!/usr/bin/env python3

"""Pushed selfspy db to endpoint"""

import subprocess
import requests
import time

tables={
    'click': 0,
    'geometry': 0,
    'keys': 0,
    'process': 0,
    'window': 0,
}

def getmax(table):
    return subprocess.getoutput("echo 'select MAX(id) from {};' | sqlite3 ~/.selfspy/selfspy.sqlite".format(table))

def getrows(table, start, stop):
    stmt = """
.mode insert {0}
select * from {0} where id > {1} and id <= {2};""".format(table, start, stop)
    print(stmt)
    return subprocess.getoutput("echo '{}' | sqlite3 ~/.selfspy/selfspy.sqlite".format(stmt))

def push(body):
    requests.post('http://172.31.3.62:5000/ingest', data = {'newData':body})

while True:
    for table, prevmax in tables.items():
        start = prevmax
        end = getmax(table)
        rows = getrows(table, start, end)
        push(rows)
        print("successfully pushed")
        tables[table] = end
    time.sleep(20)

