#!/usr/bin/env python3

"""Pushed selfspy db to endpoint"""

import subprocess
import requests
import time
import os

server=os.getenv('SPY_SERVER', 'http://localhost:5000')
interval=os.getenv('SPY_INTERVAL', 1)

tables={
    'click': 0,
    'geometry': 0,
    'keys': 0,
    'process': 0,
    'window': 0,
}

def getmax(table):
    return subprocess.getoutput("echo 'select MAX(id) from {};' | sqlite3 ~/.selfspy/selfspy.sqlite".format(table))

def getrows(table, start, stop):
    stmt = """
.mode insert {0}
select * from {0} where id > {1} and id <= {2};""".format(table, start, stop)
    return subprocess.getoutput("echo '{}' | sqlite3 ~/.selfspy/selfspy.sqlite".format(stmt))

def push(body):
    requests.post('{}/ingest'.format(server), json={'spyData':body})

while True:
    for table, prevmax in tables.items():
        start = prevmax
        end = getmax(table)
        rows = getrows(table, start, end)
        push(rows)
        tables[table] = end
    time.sleep(interval)

